<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheZone.Application\TheZone.Application.csproj" />
    <ProjectReference Include="..\TheZone.Infrastructure\TheZone.Infrastructure.csproj" />
    <ProjectReference Include="..\TheZone.Persistence\TheZone.Persistence.csproj" />
    <ProjectReference Include="..\TheZone.Contracts\TheZone.Contracts.csproj" />
  </ItemGroup>

</Project>
